# Generated by Django 4.2.29 on 2026-03-20 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mcp_store", "0004_rename_twig_callback_url_to_posthog_code_callback_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcpserver",
            name="oauth_provider_kind",
        ),
    ]
