# Generated by Django 4.2.27 on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1050_rename_slack_twig_to_posthog_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DucklingBackfillRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("data_type", models.CharField(max_length=20)),
                ("partition_key", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("workflow_id", models.CharField(blank=True, default="", max_length=255)),
                ("error_message", models.TextField(blank=True, default="")),
                ("records_exported", models.IntegerField(default=0)),
                ("bytes_exported", models.BigIntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duckling_backfill_runs",
                        to="posthog.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duckling backfill run",
                "verbose_name_plural": "Duckling backfill runs",
                "db_table": "posthog_ducklingbackfillrun",
                "unique_together": {("team", "data_type", "partition_key")},
                "indexes": [
                    models.Index(
                        fields=["data_type", "status"],
                        name="idx_ducklingbackfill_type_stat",
                    ),
                ],
            },
        ),
    ]
