# Generated by Django 4.2.29 on 2026-03-19 10:06

from django.db import migrations


def update_content_types(apps, schema_editor):
    """Update ContentType for Link model from posthog to links app."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="posthog", model="link").update(app_label="links")


def reverse_content_types(apps, schema_editor):
    """Reverse ContentType update for Link model."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="links", model="link").update(app_label="posthog")


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1055_cohort_last_backfill_person_properties_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Link",
                ),
            ],
            database_operations=[
                migrations.RunPython(update_content_types, reverse_content_types),
            ],
        ),
    ]
