# Generated by Django 4.2.29 on 2026-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1056_migrate_experiments_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="hogflow",
            name="schedule_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
