# Generated by Django 4.2.29 on 2026-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0012_alter_signalreportartefact_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalreport",
            name="run_count",
            field=models.IntegerField(default=0),
        ),
    ]
